[package]
name = "cut_creator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.23.0"
egui = "0.23.0"
egui_plot = "0.23.0"
env_logger = "0.10.0"
hound = "3.5.1"
image = "0.24.7"
rfd = "0.12.0"
splines = "4.3.0"
wav = "1.0.0"

[profile.dev]
overflow-checks = false
